### ISSUE TITLE
Better TOML_EXCEPTIONS=0 support

### ISSUE THREAD

**Issue by bjadamson** [marzer/tomlplusplus#13]
**Is your feature request related to a problem? Please describe.**
I'm in the middle of transitioning from some exceptions to no exceptions in my code base. I switched my old toml parser to toml++, but I'm currently still in the process of rewriting the rest of my code base. Since I'm still working on that, I opted into taking toml++ but using the TOML_EXCEPTIONS=0 setting in my cmake file.

toml++ tries to be intelligent and automatically determine the value of TOML_EXCEPTIONS based on a few things:

https://github.com/marzer/tomlplusplus/blob/master/include/toml%2B%2B/toml_common.h#L147-L157
```c++
#if defined(__EXCEPTIONS) || defined(__cpp_exceptions) || defined(_CPPUNWIND)
```

However this completely brakes my use case, and I have to change toml_common.h to disable these checks.

**Describe the solution you'd like**
I propose adding a #ifndef TOML_EXCEPTIONS around this test, that way if the user (me) has explicitly opted for one way or the other, the library doesn't try and do anything automatically.

**Describe alternatives you've considered**
none

**Comment by marzer** [comment]
Oh, of course, you still have to have exceptions enabled as you transition, but I'm treating them as all-or-nothing. This should be pretty easy to work around. Thanks!

**Comment by marzer** [comment]
I should add that this isn't as a trivial as it appears; the reason I'm doing it automatically is so that `TOML_MAY_THROW` is nominally correct _everywhere_, not just on toml++ methods that actually contain a `throw` statement, since in C++17 `noexcept` is part of the type system.

Not the end of the world, it just means that to keep that nice bit of logic i need _two_ versions of `TOML_MAY_THROW`; one that acts according to the compiler's exception mode, and one that honours the exception mode _and_ the user's choice w.r.t. `TOML_EXCEPTIONS`.

**Comment by marzer** [comment]
...actually after thinking about it some more, maintaining both 'levels' of exception awareness isn't worth the trouble. I'll just go with the simpler solution and evolve it later if necessary.
