### ISSUE TITLE
Accept std::filesystem::path in parse_file

### ISSUE THREAD

**Issue by hellow554** [marzer/tomlplusplus#149]
Currently [`parse_file`](https://marzer.github.io/tomlplusplus/namespacetoml.html#a8dbc58dad43c3b66f4476a7131f5741a) accepts a string_view.

In order to use a `std::filesystem::path` I would need to call `native` on it.

It would be nice, if `parse_file` would accept a `std::filesystem::path` directly.

**Comment by marzer** [comment]
I have considered adding this in the past but chose not to because `<filesystem>` is very expensive to compile ([ref 1](https://www.reddit.com/r/cpp/comments/eumou7/stl_header_token_parsing_benchmarks_for_vs2017/), [ref 2](https://artificial-mind.net/projects/compile-health/)). I don't really want to force it on most who will be happy with plain strings.

**Comment by marzer** [comment]
Paths are implicitly convertible to their native string type, aren't they? This might 'just work' already?

ref https://en.cppreference.com/w/cpp/filesystem/path/native

**Comment by hellow554** [comment]
> I have considered adding this in the past but chose not to because <filesystem> is very expensive to compile ([ref 1](https://www.reddit.com/r/cpp/comments/eumou7/stl_header_token_parsing_benchmarks_for_vs2017/), [ref 2](https://artificial-mind.net/projects/compile-health/)). I don't really want to force it on most who will be happy with plain strings.

I understand that, thanks for the explanation ;)

> Paths are implicitly convertible to their native string type, aren't they? This might 'just work' already?

No :( https://godbolt.org/z/dT5nxTsn6

**Comment by marzer** [comment]
> No :( [godbolt.org/z/dT5nxTsn6](https://godbolt.org/z/dT5nxTsn6)

Oh boo. I guess because in that scenario there's multiple conversions that are OK so it's ambiguous.

Well I might consider adding an option to enable a `std::filesystem::path` overload, something like `TOML_ENABLE_STD_FS_COMPAT` or some such.

**Comment by UMU618** [comment]
I'd like to have `toml::parse_file(std::filesystem::path)`.

**Comment by jwmelto** [comment]
While `string_view` is nice and lightweight, `toml::parse_file` is by definition dealing with files, so it would be most natural if `std::filesystem::path` were overloaded. Please implement this.

**Comment by hnOsmium0001** [comment]
Another consideration is that `toml::parse_file(std::wstring_view)` currently converts it to UTF-8 first, and then passing it to `std::ifstream`. This has the potential issue if
1. Platform is Windows
2. Process ANSI codepage is not UTF-8/65001 (ideally, yes, we want this to be true but it's not something that be assumed everywhere)

In which case `std::ifstream` will then interpret the path incorrectly. Of course, this can be worked around without adding `std::filesystem::path` support, but it will be a leaky abstraction[1].

---

Just for more perspectives. I am by no meanings request it again after the issue is reasonable closed.
If you have the same issue, I'm currently working around it by just copying the `toml::DETAILS::do_parse_file()` function out, which is around 10 lines only.

```cpp
toml::table toml::parse_file(const std::filesystem::path& path) {
    std::ifstream file;
    char fileBuffer[sizeof(void*) * 1024];
    file.rdbuf()->pubsetbuf(fileBuffer, sizeof(fileBuffer));
    // This should use the -W version of CreateFile, etc. because open() takes an overload that handles fs::path directly
    // Unlike toml++, which doesn't take fs::path, so we have to pass in std::wstring, which then gets converted to UTF-8 nicely but then relies on the codepage for the -A versions
    file.open(path, std::ios::in | std::ios::binary);
    if (!file.is_open()) 
        throw toml::parse_error("File could not be opened for reading", source_position{}, std::make_shared<const std::string>(path.string()));

    return toml::parse(file);
}
```

---

[1] Only MSVC STL provides a wchar_t constructor for `std::fstream`, so if we detect MSVC STL we can convert `std::string_view` and `std::u8string_view` to wide char, and then using that. On other standard libraries, as far as I'm aware, without using `<filesystem>` the only option is going to be call win32 APIs directly.

**Comment by marzer** [comment]
These are some good points. I will revisit this in some form eventually :)
