### ISSUE TITLE
Support options in Conan

### ISSUE THREAD

**Issue by xoorath** [marzer/tomlplusplus#227]
Hey,

It would be nice to be able to set the [configuration options](https://github.com/marzer/tomlplusplus?tab=readme-ov-file#configuration) from conan as settings.

Ping @prince-chrismc  for your thoughts as well since you're credited with the conancenter addition.

Cheers,

**Comment by marzer** [comment]
Sure, if someone wants to add this, I'm all for it. I know nothing about conan, though - as you've noted, that integration was provided by someone else 😅

**Comment by prince-chrismc** [comment]
IIRC Since this is header only, there's no value to a conan package... adding options would change the package ID but the contents would be exactly the same. This would trick conan into rebuilding and there ways to work around this... but it's always better to aligned with the official documentation which says "define these before you include" so there's no special conan logic interfering with users.

it's likely better to configure this at the project level of your cmake :)

**Comment by marzer** [comment]
OH, right, of-course; if the conan integration just uses it in header-only mode, then there's no reason to bother 😅 

I assumed it was consuming it as a regular pre-compiled library.

**Comment by marzer** [comment]
> For what it's worth: there is totally still value in using a package manager for header-only libraries. 

Nobody is telling you not to use a package manager for header-only libraries. We're saying there's not really much point in adding excessive configuration to the package manager for it, since you can set the flags in your build system directly. You can probably already propagate that right now using whatever build system you have conan integrated into.

**Comment by prince-chrismc** [comment]
Thanks marzer for clarifying. I preach package management (and devops)! [here's a list i wrote of most of the package managers in the ecosystem](https://moderncppdevops.com/pkg-mngr-roundup/).

I do understand the appeal of managing everything through Conan, the options API is the most obvious place. however that has ramifications on the package graph and might cause downstream recipes to rebuild unnecessarily. It's usually a cost you dont want to pay.

I would actually recommend using the cxxflags in a profile or from the consumer's recipe depending on how many build graphs you have.

PS I used to be on the Conan team between that original recipe and today :)

**Comment by xoorath** [comment]
Thanks both! Appreciate the clarification. 

I think I do want to expose options in Conan so for my use case I can indicate I depend on tomlplusplus but don't want exceptions all in the same place through Conan. 

If that doesn't sound like something you (or your users) would want, I can totally just define that in my build system instead of through conan options. 

If you think it's reasonable to expose options through conan: would you want that to be just some subset of options, or would you want all options? Do you care?

**Comment by marzer** [comment]
> would you want all options

Definitely not all of them - there's quite a lot! Opting out of exceptions is probably the only one that has broad appeal, methinks.
