### ISSUE TITLE
Installed pkg-config contains the wrong include directory

### ISSUE THREAD

**Issue by traversaro** [marzer/tomlplusplus#23]
## Environment
**Compiler:**  
MSVC 2019 

**C++ standard mode (e.g. 17, 20, 'latest'):**  
C++17

**Target arch (e.g. x64):**  
x64

## Describe the bug
The generated pkg-config `.pc` is the following: 
~~~
$ cat toml++.pc
prefix=C:/src/tomlplusplus/build/install
libdir=${prefix}/lib
includedir=${prefix}/include

Name: toml++
Description: Header-only TOML config file parser and serializer for modern C++
Version: 1.1.0
Cflags:-I${includedir}/toml++
~~~

and it specifies that include directories are `C:/src/tomlplusplus/build/install/toml++`, meaning that a user should include toml++'s headers as: 
~~~
#include <toml.h>
~~~
while according to the readme (https://github.com/marzer/tomlplusplus#-regular-flavour) the correct way of including them is: 
~~~
#include <toml++/toml.h>
~~~

So I guess that we should drop the `subdirs` argument from https://github.com/marzer/tomlplusplus/blob/764e6dd032fe67b6434183c0510e36b820498de6/meson.build, that do you think @marzer @ximion ?

**Comment by marzer** [comment]
@traversaro `#include <toml++/toml.h>` is indeed the canonical `#include` for the 'installed' version, since I can't rule out that users won't have other files called 'toml.h' on their include path - forcing the `toml++/` prefix eliminates that possibility.

I haven't done much testing with that part of the build configuration; is `#include <toml++/toml.h>` what you need to do if the `subdirs` part is removed?

**Comment by marzer** [comment]
@traversaro Never mind my last question; I went to read the documentation of meson's pkg-config module and answered it for myself. The fix for this is up now.

**Comment by traversaro** [comment]
Thanks!

**Comment by ximion** [comment]
Makes sense to me! Thanks for noticing!
