### ISSUE TITLE
toml::array::is_homogeneous doesn't set the node parameter

### ISSUE THREAD

**Issue by Forbinn** [marzer/tomlplusplus#231]
## Environment
**toml++ version and/or commit hash:** 
- Toml version: `3.4.0`
- Provider: `conan`

**Compiler:**  
- GCC version `10.4.0`
- Also tested with GCC version `13.3.1`

**C++ standard mode:**  
- C++ 17 `-std=c++17`

**Target arch:**  
- Linux x86_64

**Library configuration overrides:**  
- Everything is default. No flags specified.

**Relevant compilation flags:**  
- `-O1`

## Describe the bug
While using the library in my project, I've use the `toml::array::is_homogeneous` function at some point, which worked fine until I compiled my code in Release mode. In Release mode the 2nd parameter of this function (which is a ref to a pointer to a `toml::node`) started being `nullptr`. After looking at my code I didn't found anything strange so I have started working on a small example that reproduces the issue and you can find it in the next section.

TBO I'm not sure this bug is related to this library but I wanted to start somewhere as there may still be a bug in the code I provided.

Here is a table that shows when the bug appears and not depending on compiler flags:
| Condition | Result |
|--------|--------|
| Release, -O0 | OK |
| Release, -O1 | KO |
| Release, -O2 | KO |
| Release, -O3 | KO | 
| Debug | OK | 

Also removing the `const` from `n` makes the problem disappear in `-O3` Release mode but not in `-O1` or `-O2` ¯\\\_(ツ)\_/¯.

## Steps to reproduce (or a small repro code sample)
```cpp
#include <iostream>
#include <toml++/toml.hpp>

using namespace std::string_view_literals;

int main()
{
    static constexpr std::string_view some_toml = R"(
        [section]
        vec = [1, 2, "wrong"]
    )"sv;

    auto tbl = toml::parse(some_toml);
    auto sec = tbl["section"];
    auto vec = sec["vec"].as_array();

    if (vec != nullptr && !vec->empty())
    {
        toml::node const * n = nullptr;
        auto homogeneous = vec->is_homogeneous(toml::node_type::integer, n);

        std::cout << "Result: " << (n == nullptr ? "KO" : "OK") << std::endl;
    }
}
```

**Comment by marzer** [comment]
Hmmmn, yeah, looks like optimizer shenanigans. Thanks for letting me know.

**Comment by Forbinn** [comment]
Thank you for your quick response time. Just for my knowledge and before I go reporting this to the GCC team, you confirm that I use your library correctly in this context? Also, are you able to reproduce the issue?

**Comment by marzer** [comment]
> Also, are you able to reproduce the issue?

I don't really have time currently, I'm about to board a plane 😅 But, it appears you are using them correctly. The intention of those functions is:

- for you to be able to query if an array is homogeneous
- if it is not, be notified of the first mismatching element
- for that to work with either const or non-const pointers

I've just reviewed the implementation and I can't see anything overtly UB or otherwise suspicious. The only thing that might play a role is the functions being marked as `pure`, which may not be correct (I forget exactly what the GNU semantics are regarding purity and outparams now, it's been a long time). If you have a moment, mind testing this for me? It should just be a matter of removing `TOML_PURE_GETTER` [here](https://github.com/marzer/tomlplusplus/blob/b43f8a032a77872b200899bc4cdd90b7bd329c48/include/toml%2B%2B/impl/array.hpp#L421-L427) and [here](https://github.com/marzer/tomlplusplus/blob/b43f8a032a77872b200899bc4cdd90b7bd329c48/include/toml%2B%2B/impl/array.inl#L160-L190).

**Comment by Forbinn** [comment]
Very good catch, I think that's the issue. I tried by removing them where you pointed at and now it works.

The reason is stated in the manual of GCC for the pure attribute:
`The pure attribute prohibits a function from modifying the state of the program that is observable by means other than inspecting the function’s return value.`
(Source: https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#index-pure-function-attribute)

**Comment by marzer** [comment]
Excellent, thanks for testing it for me.

**Comment by marzer** [comment]
Have fixed this in main now, thanks for the report!

**Comment by Forbinn** [comment]
I just saw that, thank you for your work.
