### ISSUE TITLE
array insertion fails const iterator conversion

### ISSUE THREAD

**Issue by ned14** [marzer/tomlplusplus#32]
```c++
toml::array to, from;
for(size_t n = 0; n < from.size(); n++)
{
  to.insert(to.end(), std::move(from[n]));  // fails with cannot convert argument 1 from 'toml::array::iterator' to 'toml::array::const_iterator'
}
```

**Comment by marzer** [comment]
I've implemented a fix for the iterator conversion, though in doing so I've realized that what you're trying to do in this snippet won't work anyway; `array::operator[]` returns a `toml::node&`, and since `toml::node` is an abstract base, what you're trying to do wouldn't work without slicing the object's data.

I don't really have a good alternative without restructuring the node<=>table/array/value relationships to rely on something other than inheritance (as mentioned in #31), though I can fairly easily make the insert(pos, begin_iter, end_iter) overload work for this case.

**Comment by marzer** [comment]
The iterator conversion fix is live in 289c95c, though it doesn't solve the underlying issue I discuss above. I'll leave this issue open and await your ideas on a path forward, since my fix of the issue doesn't really get at the heart of it just yet.

**Comment by ned14** [comment]
In my code I was actually visiting the node before moving it. The code above was for exposition only. Incidentally, you currently have `visit()` as a member function, I believe it ought to be an ADL discovered free function overload. See https://en.cppreference.com/w/cpp/utility/variant/visit for the API.

I'm going to consider this closed. Thanks for the rapid fix!

**Comment by marzer** [comment]
RE visit: toml++'s `visit` has slightly different semantics to std::visit in that it allows for the visitor to be non-exhaustive; it doesn't have to be callable for _every_ possible node specialization, only the ones you need, so it's not really intended to be compatible with/related to std::visit in any way (I can't think of a situation where code would be _so_ generic that it would even make sense).
