### ISSUE TITLE
Deserialization of arrays into std::vector and std::map

### ISSUE THREAD

**Issue by levicki** [marzer/tomlplusplus#45]
A few ideas:

**Idea 1:**

```
Signature = [ 0x44, 0x4F, 0x53, 0x00 ]
```

Deserialize into `std::vector<uint8_t>` or `std::vector<uint16_t>` or `std::vector<uint32_t>` or `std::vector<uint64_t>` or their signed counterparts?

**Idea 2:**

```
Signature = [ 'M', 'S', 'C', 'F' ]
```

Deserialize into `std::string` or `std::wstring` or `std::vector<char>` or `std::vector<wchar_t>`? I understand this one might be a problem because there is no guarantee that each array index will correspond to a single character.

**Idea 3:**

```
DenominationTable = { 33 = 1000, 30 = 100, 32 = 500, 34 = 2000 }
```

Deserialize into `std::map<string, int>` or `std::map<wstring, int>`?

Please let me know what you think.

**Comment by marzer** [comment]
The serializing directly to std::string/std::wstring from a 'char' array in Idea 2 is a bit too niche to be worth implementing in the library, methinks. (especially considering that TOML doesn't even have the notion of 'char', so it would be a special case of string concatenation only when all the elements have length()==1).

The rest of it is reasonable though. Only design consideration is that TOML collections are heterogeneous, so what does this do:

```cpp
// TOML:
vals = [ 1, 2, "3", 4 ]

// C++:
std::vector<int> vals = my_config["vals"];
```

what happens to the third element? Should it be silently discarded? Raise an exception? Convert from string to int via parsing? There's no good answer here. One approach I've seen in other libraries is to provide explicit `select` methods for handling these situations:

```cpp
std::vector<int> all_integer_vals = my_config["vals"].select_all<int>(); // { 1, 2, 4 }
std::optional<int> first_integer_val = my_config["vals"].select_first();  // { 1 }
```

Unless there's strong opposition that's likely the form my implementation would take.

**Comment by levicki** [comment]
@marzer I agree on the Idea 2 being awkward.

> what happens to the third element?

I would personally expect:

1. No implicit conversion of any kind (i.e. no rounding of 2.0 to 2, or converting of "2" to 2)
2. Either return complete vector or no vector on error
3. Error raised pointing to an offending array index

My rationale is as follows:

If I am asking deserialization into `std::vector<int> then that means that I am expecting my TOML input to be an array of `int`, and any array element which is not an `int` is a syntax error in my specific TOML file even though it may be valid TOML syntax otherwise.

The method for accessing data elements of varying types already exists, this would be a convenience for situations when you know what is in the file which for machine generated files will be always true.

The reasons I would be wary of `.select_all<int>()` idea is that:

1. You have no indication an element of different type was skipped.
2. You have no way to distinguish between empty array and an array which has unacceptable values.

**Comment by marzer** [comment]
> The reasons I would be wary of .select_all<int>() idea is that:
>
>    You have no indication an element of different type was skipped.
>    You have no way to distinguish between empty array and an array which has unacceptable values.

Neither of these are true, though. Since you have a vector, and you have the node/view you got it from, you can trivially check the number of elements in the source TOML data; if it's not the same as the vector you got back, then something/everything was skipped.

**Comment by levicki** [comment]
True, I can compare sizes but I still prefer methods that can either succeed or fail rather than methods where partial success is allowed. Furthermore, comparing sizes still won't tell me on which index it failed and depending on implementation checking that all elenents are of the same type before constructing a vector out of them might even perform better. For example, you could add a property to array during parsing which would contain the type of elements if all of them are the same or a special "mixed" type which means if someone requests vector of int you can immediately fail instead of wasting time to visit each node and construct a partial result.

Please note that I am not arguing that select is bad as such (many people would probably like it) and that it shouldn't exist, just that there might be use cases where fast fail is preferred.

**Comment by marzer** [comment]
The tools you need to do this relatively cheaply and meet your criteria already exist in the library:
- [array::is_homogeneous()](https://marzer.github.io/tomlplusplus/classtoml_1_1array.html#a35ffeee7c5ba7a45dda85699af2b0f07)
- [array::size()](https://marzer.github.io/tomlplusplus/classtoml_1_1array.html#af81d7b6a1257ad766a47d9276855a7c9)
- [node_view::as_array()](https://marzer.github.io/tomlplusplus/classtoml_1_1node__view.html#a3b55b8d3689a041829a538018643795d)

e.g.:

```cpp
// TOML
Signature = [ 0x44, 0x4F, 0x53, 0x00 ]

// C++
toml::array* sig = my_config["Signature"].as_array();
if (sig && sig->size() == 4 && sig->is_homogeneous<toml::node_type::integer>())
{
	// do stuff with an array that has exactly four integer elements
}
else
	explode_all_the_things();
```

The only concern not really covered in the above example is this:


> Furthermore, comparing sizes still won't tell me on which index it failed

If you're just interested in generating an error message for the author of the configuration file, there's no useful difference between `"Signature was not an array of 4 integers"` and `"Signature was not an array of 4 integers, index 2 was <blah>"`. Potentially it might matter if you're machine-generating extremely large arrays or using TOML as an actual data serialization format, but TOML is the wrong tool for that job - it's a format meant for human-readable/editable config files.

Even still, if you really, _really_ need to identify erroneous elements then it would require relatively little work to wrap something like the above example in a helper function and scan through the array in the error case. Doing so would allow you to get the element's TOML source line and column number too, which for error reporting purposes is likely to be much more meaningful than an array index.


> For example, you could add a property to array during parsing

While this would speed up homogeneity checks (being a simple read of a bitmask member variable), it would slow down insertions (bit-and for every new element) and _greatly_ slow down deletions (full scan of whole array necessary). I could get around these issues by adding even more state to the array objects (e.g. a counter of each element type), though I'd rather not do that.


> Please note that I am not arguing

Did I give you the impression that I was arguing with you? If so, I'm not, nor have I been at any point of our correspondence. I'm just explaining my reasoning for how the library is, and how it might be in future.

**Comment by levicki** [comment]
> The tools you need to do this relatively cheaply and meet your criteria already exist in the library

Thanks, wasn't aware of `is_homogeneous()` method.

> there's no useful difference between "Signature was not an array of 4 integers" and "Signature was not an array of 4 integers, index 2 was <blah>". 

There is if an array size is not expected to be fixed. In other words, the message wouldn't be "Array length is not 4", but "Array element 16 of 54 is not an integer". I think that would be a helpful message for a human who has to fix it.

> Did I give you the impression that I was arguing with you?

Of course not! Sorry if it looked like that.

When I said "Please note that I am not arguing that select is bad as such" I simply wanted to state that I am not trying to argue against your idea of how to develop your own library :-)

**Comment by marzer** [comment]
Just want to let you know that I haven't forgotten about this; I plan to prototype an implementation this weekend (same for your other feature suggestion #43).

**Comment by levicki** [comment]
@marzer You probably meant to link to #44. Many thanks for all your work.

**Comment by marzer** [comment]
Oh, yup, definitely meant #44 ^_^

**Comment by marzer** [comment]
I've made a start on this. Have just pushed an update that allows you to use `is_homogeneous` on _any_ node or node_view, not just arrays, with an an additional overload for detecting the fail-causing element. Means you can do stuff like this:

```cpp
// TOML - my_config_file.toml
Signature = [ 0x44, 0x4F, "0x53", 0x00 ]

// C++
auto my_config = toml::parse_file("my_config_file.toml");
toml::node* bad_node{};
if (!my_config["Signature"].is_homogenous(toml::node_type::integer, bad_node))
{
	std::cerr << "'Signature' must contain only integers (saw a " << bad_node->type() << " element at "
		<< bad_node->source().begin << ")\n";
}

// output
'Signature' must contain only integers (saw a string element at line 1, column 28)
```

**Comment by levicki** [comment]
That's awesome! Thanks!

**Comment by julianxhokaxhiu** [comment]
Sorry to hijack this issue but it looks like close to what I need at the current state.

I currently have a configuration file that looks like this more or less:
```toml
shuffle = [ 1, 2, 3 ]
```

The idea is obtain the value of the key `shuffle` into a usable array. I did try to assign the parse_result object via the `shuffle` key to an `std::vector<int>` but it seems it doesn't work. I saw I can use `.as_array()` to iterate on values in the node itself, is this the current and only way to deserialize an array into another STL container?

Example code:
```cpp
auto my_config = toml::parse_file("my_config_file.toml");
std::vector<int> arr = my_config["shuffle"]; // not working
std::vector<int> arr = my_config["shuffle"].value_or(std::vector<int>()); // tomlplusplus complains is not a valid known type gives a list of supported ones
```

Thank you in advance :)

**Comment by marzer** [comment]
@julianxhokaxhiu correct, currently those assignments aren't possible and you'd need to get the array and iterate over it directly.

I still plan on implementing this but lately I've really only had time for bug fixes, sadly.

**Comment by julianxhokaxhiu** [comment]
> correct, currently those assignments aren't possible and you'd need to get the array and iterate over it directly.

Thank you for the kind reply. I'll get used to this way then :) and thank you also for this great library, I'm really happy about it!

Cheers

**Comment by levicki** [comment]
@marzer Can you please let me know what is the status of the idea 3 from this issue? Is it possible to deserialize into `std::map` now? If not, do you plan to support it and do you have at least a rough ETA?

**Comment by marzer** [comment]
Not possible yet, though I plan to include it in v3. No firm ETA, though I'm hoping to do another batch of toml++ work in January, so maybe then.

**Comment by levicki** [comment]
@marzer Thanks for clarifying. Off the top of your head, what would be the best way to implement it manually? Would array and visit work ok?

**Comment by julianxhokaxhiu** [comment]
Here you can find an example: https://github.com/marzer/tomlplusplus/blob/9aa7cd82183bfaa8500893276ad2592412c3beb3/docs/pages/main_page.dox#L238

**Comment by marzer** [comment]
Yup, the example @julianxhokaxhiu cited above is proably the simplest base to build on.

**Comment by levicki** [comment]
@marzer I will try that, thanks.

**Comment by levicki** [comment]
@marzer Sadly that won't work for my example.

```
[Section]
DenominationTable = { 33 = 1000, 30 = 100, 32 = 500, 34 = 2000 }
```
Getting `DenominationTable` from this config file as `toml::array` to iterate over it is not possible (I am getting back `nullptr`).

I checked the type of `DenominationTable` entry and `is_table()` returns true for it.

I see that it is internally serialized as a `map<string, int>` and that is exactly what I want to get out of it, I just have no idea how.

**Comment by marzer** [comment]
Oh, I misunderstood what you were trying to do. Of course `as_array` returns nullptr on a node that isn't array, since it isn't an array!

You can iterate over tables using the standard `for (auto&& [key, val] : table)` syntax just like with `std::map`, so if you were to cast the `DenominationTable` node to a `toml::table` using `as_table()` , the example above with the visitation trickery is still more-or-less  what you need.

**Comment by marzer** [comment]
You're right, I don't seem to have put an example of that anywhere in the 'proper' documentation. There is one in the repository README, however:

![image](https://user-images.githubusercontent.com/3958019/146581528-ccf1ddf4-ccd6-4e77-9a4c-a22d86c2352d.png)

I should probably put that example in the `toml::table` HTML docs too.

**Comment by levicki** [comment]
@marzer I missed that one completely.

You are right, it should be in HTML docs, and perhaps it should use `{}` TOML format as a table example.

In this case I need both keys and values, is `v.visit` going to be adequate for that or should something be changed? I must admit that this level of C++ is way over my head.

**Comment by marzer** [comment]
Yeah, you'll already have the key from the `for` loop, so you can capture that in the lambda. C++ has some weird rules about capturing structured bindings in lambdas though so you sorta have to capture it indirectly, but it's still perfectly doable. Something like this:

```cpp

std::map<std::string, int> my_map;
toml::table& denom_table = *section->["DenominationTable"].as_table();
for (auto&& [key_, val] : denom_table)
{
	// key_ is a reference to a std::string (or a toml::key in v3)
	// val is a reference to a toml::node
	val.visit([&, key_ptr = &key_](auto& concrete_value)
	{
		// inside this scope 'concrete_value' is a reference to the actual toml::value<>

		if constexpr (toml::is_integer<decltype(concrete_value)>)
		{
			// it's a toml::value<int64_t>
			
			my_map[*key_ptr] = static_cast<int>(concrete_value.get());
		}
	});
}

```

**Comment by marzer** [comment]
You can also do it without using visit at all:

```cpp
std::map<std::string, int> my_map;
toml::table& denom_table = *config["Section"]["DenominationTable"].as_table();
for (auto&& [key, val] : denom_table)
{
	my_map[key] = val.value<int>();
}
```

Though you might need to use visitation if you want to do more advanced error handling etc.

**Comment by levicki** [comment]
> C++ has some weird rules about capturing structured bindings in lambdas though so you sorta have to capture it indirectly, but it's still perfectly doable.

That was the exact sharp edge on which I caught my sleeve, figuratively speaking.

> You can also do it without using visit at all:

That almost looks like normal code now 🤣 

Is it possible to do error checking in that version? I can still call `val.is_integer()`, right?

**Comment by marzer** [comment]
> Btw, the shorter code is throwing compile error

Oh, yeah, I forgot `value()` returns a `std::optional`. It'll be empty if there was no value or it wasn't a compatible type.

> Is it possible to do error checking in that version? I can still call val.is_integer(), right?

Yeah, sure. That essentially what the `visit()` is doing under the hood anyways.

> EDIT: This works, not sure if it is correct though.

Yeah, that works too.

**Comment by marzer** [comment]
OK, so I'm doing some toml++ work this week. This issue is the first one I'm reviewing, and after giving it some additional thought, I think adding something to the library to do this directly is actually not a good idea. Given the heterogenous nature of TOML data and the myriad ways people like to do error handling, the desired semantics in the face of incompatible types and incorrectly-structured data are likely to be different for everyone, and thus should be handled in user code.

What if there's a random float, and you want only ints? Should the float be cast, or treated as an error? How is the error handled, by exception, or some other mechanism? If by exception, what about those folks who don't use exceptions? I have some special handling for them when dealing with parse failures but that is not machinery I want to duplicate everywhere (and I would probably not bother with if I were writing the library from scratch today).

And that's just one example of an unexpected type! Never mind differing array lengths, or the many different ways errors can arise in the face of more complex structured data...

No doubt with some imagination you can say "I expect it to do X", but then someone else can easily say "actually I expect it to do Y". In these situations it's generally best to provide lower-level tools to allow both to easily implement their desired solutions in their own codebases. And, as demonstrated above, that is already the case; it is already very simple to write a helper function in your own code that does this with exactly the semantics you require. You do need to be comfortable with C++17 features, but it is a C++17 library, so I don't consider that a problem I need to solve.

So, I won't be implementing this as described in the feature request. I might add additional lower-level facilities to enable this as time goes on, though, and I welcome further suggestions in that area. Eventually I might provide a hook system like nlohmann/json's `to_json()`/ `from_json()`, though that to work well I'd need to refactor the codebase to do away with inheritance and have a single discriminated union `toml` type, or similar, as that library does, which is a lot of work, and I won't have the time for a while.

**Comment by levicki** [comment]
@marzer I think we spoke about those things before but I'll try to provide some answers:

> What if there's a random float, and you want only ints? Should the float be cast, or treated as an error?

If I specified in the code that I want the `toml::array` copied into a `std::vector<int>` then having a `float` value in the data should be considered an error.

I know that someone else's preference might be what Javascript or PHP would do, but C++ at least supports type safety if used properly and it should be encouraged when designing libraries that handle data (de)serialization.

You could certainly allow silent conversion using a flag if people asked for it.

> If by exception, what about those folks who don't use exceptions?

We would need a way of knowing how many elements were in the original array (something like `cfg.as_array().length()`?), and how many were copied to a vector (i.e. the index of last copied element). If that index is equal to array length there was no error.

> never mind differing array lengths

I am not sure what you mean by this?

If you are returning a `toml::array` as a `std::vector<whatever>`, then you will return as many values as there are in the file resizing the vector accordingly, no?

It would then be our problem to check if that is too little or too much for the given array we are parsing.

> In these situations it's generally best to provide lower-level tools to allow both to easily implement their desired solutions in their own codebases.

I disagree with that conclusion.

That requires people to understand low-level data structures and inner workings of your library which IMO defeats the purpose of using your library in the first place -- people use libraries written by others so they wouldn't have to deal with that low-level stuff. If they had time and domain specific knowledge, they would have written the code they needed themselves.

> So, I won't be implementing this as described in the feature request.

Can you please clarify if that decision applies to all 3 ideas from the FR?

**Comment by marzer** [comment]
@levicki All that is simply focusing on solving _your_ specific problem. You haven't at all addressed my core concern: how do you reconcile all the different ways people might like to handle errors or unexpected data in this situation? You said "considered an error", but what does that mean? Throw an exception? Return a boolean/error code/error object? Both have pros and cons, and neither work for all cases here.

You've already in your follow-up outlined a number of "if X then Y" edge cases and different ways to handle them, perhaps without realizing you're implicitly asking me to _implement and maintain_ solutions to all of them. There is a combinatorial explosion at play here - later down the track someone else asks me to add some other way of reporting failure or a switch for some other nuance, and the 'simple' `to_vector()` function has grown to have 8 overloads each with 6 parameters. Clearly it's easier for me to provide facilities enabling people to implement this stuff themselves in whatever specific way they need it handled.

> That requires people to understand low-level data structures and inner workings of your library

It does not require knowledge of the "inner workings" of my library, as you assert, but documented parts of the public API. Of course, that requires that you are comfortable with C++17 and can read a bit of documentation; it is unfortunate that there are people for whom that is not true, but then it is not my job to upskill the unskilled or force-feed documentation at gunpoint. I can only try to facilitate one side of the social contract.

In general the library aims not to be a "kitchen sink" but to provide utilities that allow people to very easily build helpers themselves in their own codebase (e.g. is_homogeneous(), which was added expressly to aid with the use-case described in this feature request). Indeed that's why I built it originally; I was using a reflection system to deserialize complex settings structs in a game asset compiler and the existing offerings did not afford me anywhere near enough control or precision. It's the exact reason the library is "low-level" in the way that it is. One trade-off with that design is that it necessarily needs to avoid "one-size-fits-all" solutions, especially in error-handling scenarios, lest it fall prey to the combinatorics problem described above.

> which IMO defeats the purpose of using your library in the first place -- people use libraries written by others so they wouldn't have to deal with that low-level stuff

That is demonstratably false, given the reason for the library's existence outlined above. It might be the reason _you_ use a library, but please do not make broad assertions on behalf of every programmer in the world. At best you can say people use this library because they want to work with TOML in C++ and don't want to write a parser. Anything else is down to the needs of the individual.

There are two other options for parsing TOML v1.0 in C++; if you don't like something about my library and that is unlikely to change (e.g. I've explicitly outlined why something won't change soon/ever), then I encourage you to explore the alternatives. We are humans with finite lifespans and this is all free software.
