### ISSUE TITLE
value::operator == for doubles is missing some cases

### ISSUE THREAD

**Issue by Reedbeta** [marzer/tomlplusplus#51]
This bit:

```cpp
switch (pack(impl::fpclassify(lhs.val_), impl::fpclassify(rhs)))
{
    case pack(fp_class::pos_inf, fp_class::neg_inf):    [[fallthrough]];
    case pack(fp_class::pos_inf, fp_class::nan):        [[fallthrough]];
    case pack(fp_class::neg_inf, fp_class::pos_inf):    [[fallthrough]];
    case pack(fp_class::neg_inf, fp_class::nan):        [[fallthrough]];
    case pack(fp_class::nan, fp_class::pos_inf):        [[fallthrough]];
    case pack(fp_class::nan, fp_class::neg_inf):
        return false;

    case pack(fp_class::pos_inf, fp_class::pos_inf):    [[fallthrough]];
    case pack(fp_class::neg_inf, fp_class::neg_inf):    [[fallthrough]];
    case pack(fp_class::nan, fp_class::nan):
        return true;

    case pack(fp_class::ok, fp_class::ok):
        return lhs.val_ == rhs;

    TOML_NO_DEFAULT_CASE;
}
```

If I'm not mistaken, it's missing any cases for comparing an `ok` against any of the non-`ok` classes?

Also....why is this whole thing here? 😅 Regular floating-point comparison will do what you want in all the cases here except for `nan == nan` which always returns false, while you have it as true (and I'd argue it's better not to change the semantics there unexpectedly, unless you have a very good reason to do so).

**Comment by marzer** [comment]
Oof yeah you're right, seems I've missed those cases entirely.

> Also....why is this whole thing here? 

It's there because `-ffast-math` / `-ffinite-math-only` broke it; TOML configs can have infinities and nans regardless of compiler settings and I want those to be round-trippable (I forget which compiler exactly needed this, Clang I think).

> I'd argue it's better not to change the semantics there unexpectedly, unless you have a very good reason to do so

My reasoning is that it's asking "does this TOML value equal this?", not "does this float compare equal according to IEEE 754 rules?". I'm not married to this idea, though it seems a logical distinction to draw.

**Comment by marzer** [comment]
Additional context on the 'why': that operator is ultimately how value-value comparison is done when calling `table::operator == ` and `array::operator == `, so without that logic, two identical tables containing NaNs would not be 'equal', which would be surprising behavior.

Of course that problem doesn't need to be solved in `value::operator ==`, but context is context.

**Comment by marzer** [comment]
Alright, well, that's fixed.

While I was there I went back and double-checked the impact of `-ffinite-math-only`; it definitely breaks `fpclassify`/`isnan`/`isinf` (which makes sense), but I'd thought it also broke `std::numeric_limits<double>::quiet_NaN` and `std::numeric_limits<double>::infinity` on some implementations, but apparently that's not the case (or it was for me at some point, but I cannot reproduce it now). Which is nice, since that means I got to simplify quite a bit of nan/inf-related code :D

There's still the matter of `value<double>{ NaN } == NaN` returning true or false. I've kept the existing behavior for now, since it models the state of the value in the TOML config (not the value in C++-land); given this TOML:
```toml
val1 = nan
val2 = nan
```
`val1` and `val2` are equal for the purposes of the config (i.e. the answer to the question of "are these both NaN" is "yes". They're not equal according to IEEE 754 rules, but I'd argue that's not really all that useful here. If you want those semantics you can always work with the wrapped double values directly.

**Comment by marzer** [comment]
Oh also: thanks for the bug report @Reedbeta :D
