### ISSUE TITLE
Preserving original order

### ISSUE THREAD

**Issue by KangJH** [marzer/tomlplusplus#62]
**Is your feature request related to a problem? Please describe.**
Hi
Is there a way to preserve original order of toml file?
After parse() and serialization(cout << parsed_toml_node), the order in output is different to the original file. 
It seems like toml++ reorder according to alphabetical order of key name.
Can you recommend a way to preserve original order of toml file?

**Describe the solution you'd like**

**Additional context**

**Comment by marzer** [comment]
No, there no way to do this presently. Since the TOML spec doesn't consider key ordering to be meaningful, neither does this library (the only reason it is re-serialized in alphabetical order is because of the use of `std::map` under-the-hood, though this may not always be true).

I may implement this at some stage (since it relates strongly to #28), though it won't be any time soon I'm afraid.

**Comment by KangJH** [comment]
Thank you for the answer. I'll keep track #28 also. Thanks!
