### ISSUE TITLE
Allow default specification when getting table or array type

### ISSUE THREAD

**Issue by chrismurf** [marzer/tomlplusplus#70]
**Is your feature request related to a problem? Please describe.**
I use TOML to provide configuration of a variety of C++ classes, typically passing const a toml::table& to each subcomponent which it then can process.  I would like to be able to easily fall back on an empty toml::table() for missing keys on a node_view, rather than a null pointer.

**Describe the solution you'd like**
I frequently use value_or() to provide default values for individual configuration parameters.  I'd like a similar inline construct for specifying a subtable that falls back on an empty table (or even a populated one, like value_or).  Something like the below would be nice, but doesn't work today because value_or only works with primitive types.

```C++
Component::Component(const toml::table& cfg) {
    _maximum_delay = cfg["maximum_delay"].value_or(toml::time({1,0,0,0}));
    _foozbar_flavor = cfg["foozbar_flavor"].value_or("Chocolate");
    _subcomponent = SubComponent(cfg["table_configured_thing"].value_or(toml::table()));
}

SubComponent::SubComponent(const toml::table& cfg) {
    _ice_cream_cones = cfg["ice_cream_cones"].value_or(1000);
}

```

**Additional context**
Null pointers (such as returned by as_table()) require explicit checking, which interrupts the flow of (otherwise very nice!) toml++ usage.  I'd like to be able to fall back on default values for missing or non-table keys.

I'm also surprised by the use of null pointers here, instead of `std::optional<toml::table>` - I appreciate optional's use in other parts of the library.

Thank you!

**Comment by marzer** [comment]
Aye there's an obvious gap here (shares similarities https://github.com/marzer/tomlplusplus/issues/45). It's complicated by the fact that TOML tables and arrays are heterogeneous; there's no built-in STD type that would approximate that without a frankenstein solution like `std::vector<std::variant<...>>` (and I _really_ don't want to force `std::variant` on people...).

Returning new instances of `toml::table` or `toml::array` isn't great either, though; `toml++` values/tables/arrays are related by inheritance, thus collections of them rely on heap allocation. That's also the reasoning behind this:
> I'm also surprised by the use of null pointers here, instead of std::optional\<toml::table\> - I appreciate optional's use in other parts of the library.

`as_table()`, `as_array()` and friends are just down-casts.

Performance concerns aside, `value()` and `value_or()` are explicitly for the purpose of returning TOML values, as distinct from _collections_ of them. From an API design standpoint I'd like to keep it that way, since the library draws a clear distiction between TOML values and not-values throughout.

All that being said, your example above is a good argument for the need to fill this gap, so consider it on my to-do list. Sadly I'm currently neck-deep in other things and won't have time to iterate on this for a while (there's a few other `toml++` things in that same boat, too...); my interim solution would be to use a helper function to reduce verbosity. Here's an (untested) example:

```cpp
// helper:

template <typename TSubComponent>
[[nodiscard]]
TSubComponent construct_from_subtable(const toml::table& cfg, std::string_view key, toml::table&& fallback = {})
{
	if (auto tbl = cfg[key].as_table(); tbl)
		return TSubComponent{ *tbl };
	return TSubComponent{ std::move(fallback) };
}

// usages:

_subcomponent = construct_from_subtable<SubComponent>("table_configured_thing");
_subcomponent2 = construct_from_subtable<SubComponent2>("table_configured_thing_2", toml::table{{  { "foo", "bar" } }});

```

**Comment by marzer** [comment]
Also thanks for the suggestion!

**Comment by chrismurf** [comment]
@marzer - thank you!  I appreciate the very useful library, and you taking the time to walk through the current state of affairs.  Have a good holiday season.

**Comment by chrismurf** [comment]
@marzer - has there been any code changes that impact this?  I understand if you're just closing to cleanup the issue list - your previously described workaround is still working well in our codebase.  Just want to make sure I didn't miss a relevant change.

Cheers!

**Comment by chrismurf** [comment]
Not disappointing at all, we've been using TOML++ to great effect and I really appreciate your efforts and responsiveness.  Thank you!   I'll check out at_path - hadn't seen that yet.

**Comment by marzer** [comment]
> Not disappointing at all, we've been using TOML++ to great effect

Great to hear :)

>  I'll check out at_path

I've just realized that It's not obvious from that doc page - there's also member function versions in `node` and `node_view` (as well as `parse_result` if you're working with exceptions disabled). 

There's also lots of other QoL improvements in v3, you can see the full list in the new [CHANGELOG.md](https://github.com/marzer/tomlplusplus/blob/master/CHANGELOG.md)
